### ISSUE TITLE
Trouble running IDM-VTON and StoryDiffusion Comics

### ISSUE THREAD

**Issue by Felino707** [pinokiofactory/factory#54]
Hi,
I have a problem with these two apps IDM-VTON and StoryDiffusion Comics when I try to open them. 
At the end of installation of IDM-VTON and StoryDiffusion Comics I get this error:

ENOENT: no such file or directory, stat 'C:\pinokio\api\idm-vton.git\{{input.event[0]}}'

ENOENT: no such file or directory, stat 'C:\pinokio\api\storydiffusion-comics.git\{{input.event[0]}}'

The error in the terminal after I started the app for IDM-VTON:

Microsoft Windows [Version 10.0.22621.4317]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\pinokio\api\idm-vton.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\pinokio\api\idm-vton.git\app\env\Scripts\activate C:\pinokio\api\idm-vton.git\app\env && python app.py

C:\pinokio\api\idm-vton.git\app\env\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\pinokio\api\idm-vton.git\app\env\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\pinokio\api\idm-vton.git\app\env\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\pinokio\api\idm-vton.git\app\app.py", line 3, in <module>
    from src.tryon_pipeline import StableDiffusionXLInpaintPipeline as TryonPipeline
  File "C:\pinokio\api\idm-vton.git\app\src\tryon_pipeline.py", line 29, in <module>
    from diffusers.image_processor import PipelineImageInput, VaeImageProcessor
  File "C:\pinokio\api\idm-vton.git\app\env\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\pinokio\api\idm-vton.git\app\env\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\pinokio\api\idm-vton.git\app\env\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\pinokio\api\idm-vton.git\app\env\lib\site-packages\huggingface_hub\__init__.py)

(env) (base) C:\pinokio\api\idm-vton.git\app>

The error in the terminal after I started the app for StoryDiffusion Comics:

Microsoft Windows [Version 10.0.22621.4317]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\pinokio\api\storydiffusion-comics.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\pinokio\api\storydiffusion-comics.git\app\env\Scripts\activate C:\pinokio\api\storydiffusion-comics.git\app\env && python app.py

C:\pinokio\api\storydiffusion-comics.git\app\env\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\pinokio\api\storydiffusion-comics.git\app\env\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\pinokio\api\storydiffusion-comics.git\app\env\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\pinokio\api\storydiffusion-comics.git\app\app.py", line 15, in <module>
    from utils.gradio_utils import is_torch2_available
  File "C:\pinokio\api\storydiffusion-comics.git\app\utils\__init__.py", line 2, in <module>
    from .pipeline import PhotoMakerStableDiffusionXLPipeline
  File "C:\pinokio\api\storydiffusion-comics.git\app\utils\pipeline.py", line 13, in <module>
    from diffusers import StableDiffusionXLPipeline
  File "C:\pinokio\api\storydiffusion-comics.git\app\env\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\pinokio\api\storydiffusion-comics.git\app\env\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\pinokio\api\storydiffusion-comics.git\app\env\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\pinokio\api\storydiffusion-comics.git\app\env\lib\site-packages\huggingface_hub\__init__.py)

(env) (base) C:\pinokio\api\storydiffusion-comics.git\app>

I believe that both errors may be related, so I combined the two requests for help into one. 
PhotoMaker2 and FaceFusion runs perfectly.

**Comment by 6Morpheus6** [comment]
Hi @Felino707
Yes you are right. Both happens because huggingface_hub was updated lately and breaks several apps now.
We are about to fix them all at the moment.
To fix your apps, please close Pinokio and type **Anaconda Powershell** into your Windows Taskbar and open it.
For idm-vton copy / paste the following commands into Anaconda Powershell:
- `cd C:\pinokio\api\idm-vton.git\app`
- `env\Scripts\activate`
  - You should see a green (env) in front of your prompt now. Don't proceed if this (env) is missing!
- `pip install huggingface_hub==0.25.2`
- Once finished you can start idm-vton in pinokio

For Story diffusion, the easiest way is to restart Anaconda Powershell to leave the env
(principally you can also do it with the command `deactivate`)

For Story Diffusion copy / paste the following commands into Anaconda Powershell:
- `cd C:\pinokio\api\storydiffusion-comics.git\app`
- `env\Scripts\activate`
  - You should see a green (env) in front of your prompt now. Don't proceed if this (env) is missing!
- `pip install huggingface_hub==0.25.2`
- Once finished you can start Story Diffusion Comics in pinokio

**Comment by Felino707** [comment]
Just to thank you for your help 6Morpheus6. It works. You're the best
